import '../components/page.js'
import '../components/header.js'

import '../components/faqs/data-add.js'
import '../components/customers/data-add.js'
import '../components/users/data-add.js'
import '../components/companies/data-add.js'
import '../components/product-categories/data-add.js'
import '../components/products/data-add.js'

import '../components/faqs/data-list.js'
import '../components/customers/data-list.js'
import '../components/users/data-list.js'
import '../components/companies/data-list.js'
import '../components/product-categories/data-list.js'
import '../components/products/data-list.js'

import '../components/title.js'
import '../components/burger-menu.js'
import '../components/filter.js'
import '../components/delete.js'
import '../components/notification.js'
import '../components/crud.js'
import '../components/image-add.js'
import '../components/image-modal.js'
