import '../components/crud-form.js'
import '../components/crud-table.js'
import '../components/crud.js'
import '../components/customers/crud-form.js'
import '../components/customers/crud-table.js'
import '../components/delete-modal.js'
import '../components/image-modal.js'
import '../components/page.js'
import '../components/select-image.js'
import '../components/title.js'
import '../components/user-form.js'
import '../components/users/crud-form.js'
import '../components/users/crud-table.js'


